Making it so github workflows can see if we have memory leaks as well as adding asan capability to ./build.sh. Updating version of valkey-module as well so memory leak no longer occurs
Signed-off-by: zackcam <zackcam@amazon.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -87,6 +87,7 @@ jobs:
         git clone "${{ env.VALKEY_REPO_URL }}"
         cd valkey
         git checkout ${{ matrix.server_version }}
+        make distclean
         make -j SANITIZER=address SERVER_CFLAGS='-Werror' BUILD_TLS=module
         cp src/valkey-server ../binaries/${{ matrix.server_version }}/
     - name: Set up Python
@@ -100,4 +101,21 @@ jobs:
     - name: Update module path
       run: echo "MODULE_PATH=$(realpath target/release/libvalkey_bloom.so)" >> $GITHUB_ENV
     - name: Run integration tests 
-      run: python -m pytest --cache-clear -v "tests/" -m "not skip_for_asan"
+      run: |
+        python -m pytest --capture=sys --cache-clear -v "tests/" -m "not skip_for_asan" 2>&1 | tee test_output.tmp
+        
+        if grep -q "LeakSanitizer: detected memory leaks" test_output.tmp; then
+          RED='\033[0;31m'
+          echo -e "${RED}Memory leaks detected in the following tests:"
+          LEAKING_TESTS=$(grep -B 2 "LeakSanitizer: detected memory leaks" test_output.tmp | \
+                          grep -v "LeakSanitizer" | \
+                          grep ".*\.py::")
+          LEAK_COUNT=$(echo "$LEAKING_TESTS" | wc -l)        
+          echo "$LEAKING_TESTS" | while read -r line; do
+              echo "::error::Test with leak: $line"
+          done
+          echo -e "\n$LEAK_COUNT python integration tests have leaks detected in them"
+          rm test_output.tmp
+          exit 1
+        fi
+        rm test_output.tmp
